[package]
name = "one-wire-bus"
version = "0.1.0"
authors = ["Nathan Fox <fuchsnj@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-hal = {version="0.2.3", features=["unproven"]}